[package]
name = "boringdb"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite="0.25"
bytes="1"
flume="0.10"
parking_lot="0.11"
log="0.4"
nanorand={version="0.5", default-features=false, features=["std", "tls"]}
thiserror="1.0"

[dev-dependencies]
criterion = "0.3"
env_logger="0.8"
